#-------------------------------
# Site Settings
title: Bishal Timsina
description:


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'HOME'
      url: '/'
    - title: 'ABOUT'
      url: '/about'
    - title: 'Project'
      url: '/project'
    - title: 'Skills'
      url: '/skills'
    - title: 'Publications'
      url: '/publications'
    - title: 'Services'
      url: '/services'

    


#-------------------------------
# Google Analytics
google-analytics:  # Add your GA Tracking Id
